language: python
python:
  - "3.6"

cache:
  pip: true

stages:
  - lint
  - test
  - deploy

jobs:
  include:

    - stage: lint
      if: (branch = master) OR (type = pull_request AND head_branch = master)
      script:
        - pip install -U pylint
        - pylint torchrl experiments

    - stage: test
      if: (branch = master) OR (type = pull_request AND head_branch = master)
      script:
        - pip install -U .
        - echo "TODO!"

    - stage: docs
      if: (tag IS present) OR (branch = master)
      script:
        - pip install -U -r requirements_dev.txt
        - pushd docs && make html && popd

    - stage: deploy
      if: tag IS present
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        on:
          tags: true
