language: python
python:
  - "3.7"

cache:
  pip: true
  directories:
    - .pytest_cache/

stages:
  - name: test
    if: (branch = master) OR (type = pull_request AND head_branch = master)
  - name: deploy
    if: (tag IS present) OR (branch = master) OR (type = pull_request AND head_branch = master)

jobs:
  include:

    - stage: test
      before_script:
        - pip install .[test]
      script:
        - pytest
        - pylint setup.py torchrl experiments

    - stage: deploy
      before_script:
        - pip install -e .[docs]
      script:
        - pushd docs && make html && popd
        - cp _redirects docs/build/html
      after_success:
        - curl -LO https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz && tar -xzvf netlifyctl-linux-amd64-0.4.0.tar.gz
        - echo no | ./netlifyctl deploy -n torchrl -A $NETLIFY_ACCESS_TOKEN -P docs/build/html -m "$TRAVIS_COMMIT_MESSAGE" $([[ -z $TRAVIS_PULL_REQUEST_BRANCH && $TRAVIS_BRANCH = "master" ]] && echo "" || echo "-d")
      before_deploy:
        - echo "$TRAVIS_TAG" > VERSION
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        skip_cleanup: true
        on:
          tags: true
