name: torchrl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - ipykernel
  - ipywidgets
  - future
  - numpy
  - ruamel.yaml
  - tqdm
  - pytorch=1.2.*
  - tensorflow=1.14.*
  - tensorboard=1.14.*
  - pip:
    - gym>=0.10
